name: Dad to Daughters
favicon: null
layout_spectrum: 0.11017
typography_spectrum: 0.3546171037014574
title: Dad to Daughters
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050402'
    - '#997a6d'
    - '#331e11'
    - '#bea9a1'
    - '#ead7ca'
  brandStrength: 0.8802649031858891
  lightness: 0.16809945227578282
  saturation: 0.75
  rhythmicContrast: 0.9325694150757045
purpose: []
